import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="grid grid-rows-1 lg:grid-cols-2 md:grid-cols-1 gap-4 mx-auto container ">
        <div className="flex flex-col justify-center mt-15 pt-20 pl-5 pr-5  md:pl-20  md:pt-20  md:mt-5 ">
          <div className="pb-2">
            <span className="bg-gray-200 text-gray-500 text-xs font-semibold  rounded-full py-3 px-5">
              La nueva tecnologia en tus manos
            </span>
          </div>

          <h1 className="text-4xl font-bold sm:py-1 md:py-5 md:text-6xl sm:text-5xl">
            Desarrollamos soluciones digitales y servicios de alta experiencia
          </h1>

          <p className="sm:py-1 md:py-5 font-light">
            Desarrollamos software y tecnología innovadora. Al mismo tiempo
            brindamos soluciones con el uso de servicios de empresa lideres en
            el mercado mundial.
          </p>

          <div>
            <button
              type="button"
              className="text-white bg-sky-500 hover:bg-sky-600 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0  inline-flex items-center"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="w-4 h-4 mr-2 -ml-1"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth="2"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                ></path>
              </svg>
              Contáctanos
            </button>
          </div>
        </div>

        <div>
          <img src="assets/Banner.jpg" />
        </div>
      </div>

      <div className="grid grid-rows-1 content-center m-10">
        <h2 className="text-center text-gray-500">
          Trabajamos con servicos Top en el mundo
        </h2>
        <div className="flex justify-center">
          <div className="mx-5">
            <img
              src="assets/google.svg"
              className="w-24 h-24"
              alt="Flowbite Logo"
            />
          </div>
          <div className="mx-5">
            <img
              src="assets/Amazon-logo.svg"
              className="w-24 h-24"
              alt="Flowbite Logo"
            />
          </div>
          <div className="mx-5">
            <img
              src="assets/google.svg"
              className="w-24 h-24"
              alt="Flowbite Logo"
            />
          </div>
          <div className="mx-5">
            <img
              src="assets/google.svg"
              className="w-24 h-24"
              alt="Flowbite Logo"
            />
          </div>
        </div>
      </div>

      <div className="bg-sky-50">
        <div className="grid place-content-center h-64">
          <div className="flex flex-col justify-center text-center max-w-md">
            <h1 className="text-5xl font-bold py-5">
              Soluciones digitales modernas
            </h1>

            <p className="text-zinc-400 whitespace-normal">
              Accede al mundo moderno con poderosas herramientas tecnológicas
              que permitirán el crecimiento de tu organización
            </p>

            <div>
              <button
                type="button"
                className="text-sky-600  hover:bg-sky-50 hover:text-sky-500 focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center"
              >
                Ver más
                <svg
                  className="w-5 h-5 ml-2 -mr-1"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                    clipRule="evenodd"
                  ></path>
                </svg>
              </button>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-2 md:grid-cols-1">
          <div>
            <img src="assets/devsBanner.jpeg" />
          </div>

          <div>
            <img src="assets/devsBanner.jpeg" />
          </div>
        </div>
      </div>

      <div className="m-10">
        <div className="grid place-content-center h-64">
          <div className="flex flex-col justify-center text-center max-w-md">
            <h1 className="text-5xl font-bold py-5">
              Proyectos innovadores del futuro
            </h1>

            <p className="text-zinc-400 whitespace-normal">
              Accede al mundo moderno con poderosas herramientas tecnológicas
              que permitirán el crecimiento de tu organización
            </p>

            <div>
              <button
                type="button"
                className="text-sky-600  hover:bg-sky-50 hover:text-sky-500 focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center"
              >
                Ver más
                <svg
                  className="w-5 h-5 ml-2 -mr-1"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fillRule="evenodd"
                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                    clipRule="evenodd"
                  ></path>
                </svg>
              </button>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-3 md:grid-cols-2 mx-5">
          <div className="transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
            <div className="max-w-sm bg-white rounded-2xl shadow-md gap-10 m-10">
              <div className="flex flex-col items-center text-center pt-6">
                <img
                  className="mb-3 w-24 h-24 rounded-full shadow-lg"
                  src="assets/Conectica.png"
                  alt="Bonnie image"
                />
                <h5 className="mb-1 text-xl font-medium text-gray-900 ">
                  Conectica
                </h5>
                <span className="text-sm text-gray-500 dark:text-gray-400">
                  La plataforma de educación más completa para Latinoamerica
                </span>
                <button
                  type="button"
                  className="text-sky-600  hover:bg-sky-50 hover:text-sky-500 focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm m-5 text-center inline-flex items-center p-2.5"
                >
                  Conocer
                </button>
              </div>
            </div>
          </div>
          <div className="transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
            <div className="max-w-sm bg-white rounded-2xl shadow-md gap-10 m-10">
              <div className="flex flex-col items-center text-center pt-6">
                <img
                  className="mb-3 w-24 h-24 rounded-full shadow-lg"
                  src="assets/Conectica.png"
                  alt="Bonnie image"
                />
                <h5 className="mb-1 text-xl font-medium text-gray-900 ">
                  Turistics
                </h5>
                <span className="text-sm text-gray-500 dark:text-gray-400">
                  La plataforma de educación más completa para Latinoamerica
                </span>
                <button
                  type="button"
                  className="text-sky-600  hover:bg-sky-50 hover:text-sky-500 focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm m-5 text-center inline-flex items-center p-2.5"
                >
                  Conocer
                </button>
              </div>
            </div>
          </div>
          <div className="transition transform hover:-translate-y-1 motion-reduce:transition-none motion-reduce:hover:transform-none">
            <div className="max-w-sm bg-white rounded-2xl shadow-md gap-10 m-10">
              <div className="flex flex-col items-center text-center pt-6">
                <img
                  className="mb-3 w-24 h-24 rounded-full shadow-lg"
                  src="assets/Conectica.png"
                  alt="Bonnie image"
                />
                <h5 className="mb-1 text-xl font-medium text-gray-900 ">
                  Blogger
                </h5>
                <span className="text-sm text-gray-500 dark:text-gray-400">
                  La plataforma de educación más completa para Latinoamerica
                </span>
                <button
                  type="button"
                  className="text-sky-600  hover:bg-sky-50 hover:text-sky-500 focus:ring-4 focus:outline-none  font-medium rounded-lg text-sm m-5 text-center inline-flex items-center p-2.5"
                >
                  Conocer
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <main></main>

      <Footer />
    </div>
  );
}
